development:
  adapter: async

test:
  adapter: async

integration:
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:6379" %>

staging:
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:6379" %>

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: qa_server_production
