---
authority:
  service: ld4l_cache
search:
  -
    query: 'Barack Obama'
term:
  -
    identifier: 'http://dbpedia.org/resource/Barack_Obama'
  -
    query: Volleyball
    position: 5
    subject_uri: "http://dbpedia.org/resource/Volleyball"
    replacements:
      maxRecords: '10'
    
