---
authority:
  service: ld4l_wrapped
  context: true
search:
  #------------------
  # Connection tests
  #------------------
  -
    query: picard

  #------------------
  #  Accuracy tests
  #------------------
  -
    query: Gonzalez-Torres, Felix
    subject_uri: "https://isni.org/isni/0000000115805416"
    position: 5
    replacements:
      maxRecords: '10'
  -
    query: Johan Goeverneur
    subject_uri: "https://isni.org/isni/0000000063969856"
    position: 5
    replacements:
      maxRecords: '10'
  -
    query: 0000 0000 6396 9856
    subject_uri: "https://isni.org/isni/0000000063969856"
    position: 3
    replacements:
      maxRecords: '8'
  -
    query: University of Chicago Library
    subject_uri: "https://isni.org/isni/0000000406464287"
    position: 5
    replacements:
      maxRecords: '10'
